# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Solitary
subtitle: 胆小认生 不易相处
description: 生在任何时代，我都是痛苦的，所以不要怪时代，也不要怪我。
keywords: Stay Hungry, Stay Foolish
author: 忘生
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:  https://www.ku299.com 
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next 

# 搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #repository: git@github.com:ku66/ku66.github.io.git
  #coding: git@git.dev.tencent.com:ku66/ku66.coding.me.git,master
  #branch: master
  repo:
    github: git@github.com:ku66/ku66.github.io.git,master
    coding: git@git.dev.tencent.com:ku66/ku66.coding.me.git,master
    #cvm: root@CVM :/home/git/hexoBlog
    cvm:  root@111.231.54.15:/home/git/hexoBlog,master
   

type: baidu_url_submitter ## 这是新加的

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-wanko
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true

sitemap: 
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  url:  https://wuchen.cc/

baidu_url_submit:
  count: 100 ## 比如3，代表提交最新的三个链接
  host: https://www.ku299.com  ## 在百度站长平台中注册的域名
  token: a6xDHFUqb0jfZKw5 ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里



